package controller.TamTruTamVang;

import javafx.fxml.FXML;

import javafx.fxml.Initializable;
import javafx.scene.Node;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.ButtonType;
import javafx.scene.control.TextField;

import javafx.event.ActionEvent;
import javafx.scene.effect.SepiaTone;
import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;
import model.TamVang;
import services.TamTruTamVangService;

import java.net.URL;
import java.sql.SQLException;
import java.util.ResourceBundle;

public class dkTamVang implements Initializable {
    @FXML
    private TextField tfMaNhanKhau;
    @FXML
    private TextField tfTuNgay;
    @FXML
    private TextField tfDenNgay;
    @FXML
    private TextField tfLiDo;
    @FXML
    private TextField tfNoiTamTru;
    @FXML
    private Button btDangKy;

    // Event Listener on Button.onAction
    @FXML
    public void add(ActionEvent event) throws SQLException {
        // TODO Autogenerated
        String maNhanKhau = tfMaNhanKhau.getText();
        String noiTamTru = tfNoiTamTru.getText();
        String tuNgay = tfTuNgay.getText();
        String denNgay = tfDenNgay.getText();
        String liDo = tfLiDo.getText();


        try {
            TamVang tamVang = new TamVang(maNhanKhau, noiTamTru, tuNgay, denNgay, liDo);
            new TamTruTamVangService().themTamVang(tamVang);
        }
        catch (Exception e) {
            Alert alert = new Alert(Alert.AlertType.WARNING, "Hãy nhập vào thông tin chính xác!", ButtonType.OK);
            alert.setHeaderText(null);
            alert.showAndWait();
        }

        Stage stage = (Stage)((Node) event.getSource()).getScene().getWindow();
        stage.close();
    }

    @Override
    public void initialize(URL url, ResourceBundle resourceBundle) {
        btDangKy.addEventHandler(MouseEvent.MOUSE_MOVED, event -> btDangKy.setEffect(new SepiaTone()));
        btDangKy.addEventHandler(MouseEvent.MOUSE_EXITED, event -> btDangKy.setEffect(null));
    }
}