package controller.TamTruTamVang;
import javafx.fxml.FXML;

import javafx.fxml.Initializable;
import javafx.scene.Node;
import javafx.scene.control.*;

import javafx.event.ActionEvent;
import javafx.scene.effect.SepiaTone;
import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;
import model.TamTru;
import services.TamTruTamVangService;

import java.net.URL;
import java.sql.SQLException;
import java.time.format.DateTimeFormatter;
import java.util.ResourceBundle;

public class dkTamTru implements Initializable {
    @FXML
    private TextField tfHoTen;
    @FXML
    private TextField tfCMND;
    @FXML
    private DatePicker tfTuNgay;
    @FXML
    private DatePicker tfDenNgay;
    @FXML
    private TextField tfLiDo;
    @FXML
    private TextField tfSDT;
    @FXML
    private Button btDangKy;

    // Event Listener on Button.onAction
    @FXML
    public void add(ActionEvent event) throws SQLException {
        // TODO Autogenerated
        String hoTen = tfHoTen.getText();
        String cmnd = tfCMND.getText();
        String tuNgay = tfTuNgay.getValue().format(DateTimeFormatter.ofPattern("yyyy-MM-dd"));
        String denNgay = tfDenNgay.getValue().format(DateTimeFormatter.ofPattern("yyyy-MM-dd"));
        String liDo = tfLiDo.getText();
        String sdt = tfSDT.getText();


        try {
            TamTru tamTru = new TamTru(hoTen, cmnd,sdt, tuNgay,denNgay, liDo);
            new TamTruTamVangService().themTamTru(tamTru);
        }
        catch (Exception e) {
            Alert alert = new Alert(Alert.AlertType.WARNING, "Hãy nhập vào thông tin chính xác!", ButtonType.OK);
            alert.setHeaderText(null);
            alert.showAndWait();
        }

        Stage stage = (Stage)((Node) event.getSource()).getScene().getWindow();
        stage.close();
    }

    @Override
    public void initialize(URL url, ResourceBundle resourceBundle) {
        btDangKy.addEventHandler(MouseEvent.MOUSE_MOVED, event -> btDangKy.setEffect(new SepiaTone()));
        btDangKy.addEventHandler(MouseEvent.MOUSE_EXITED, event -> btDangKy.setEffect(null));
    }
}