package controller.TamTruTamVang;
import controller.ControllerNhanKhau;
import javafx.fxml.FXML;

import javafx.scene.Node;
import javafx.scene.control.Alert;
import javafx.scene.control.ButtonType;
import javafx.scene.control.TextField;

import javafx.event.ActionEvent;
import javafx.stage.Stage;
import model.TamTru;
import services.TamTruTamVangService;

import java.sql.SQLException;
import java.util.regex.Pattern;

public class dkTamTru {
    @FXML
    private TextField tfHoTen;
    @FXML
    private TextField tfCMND;
    @FXML
    private TextField tfTuNgay;
    @FXML
    private TextField tfDenNgay;
    @FXML
    private TextField tfLiDo;
    @FXML
    private TextField tfSDT;

    // Event Listener on Button.onAction
    @FXML
    public void add(ActionEvent event) throws SQLException {
        // TODO Autogenerated
        if(!check()) return;

        String hoTen = tfHoTen.getText();
        String cmnd = tfCMND.getText();
        String tuNgay = tfTuNgay.getText();
        String denNgay = tfDenNgay.getText();
        String liDo = tfLiDo.getText();
        String sdt = tfSDT.getText();

        TamTru tamTru = new TamTru(hoTen, cmnd,sdt, tuNgay,denNgay, liDo);
        new TamTruTamVangService().themTamTru(tamTru);
        Stage stage = (Stage)((Node) event.getSource()).getScene().getWindow();
        stage.close();
    }

    public boolean check() {
        //TODO: khoảng trắng vẫn có thể nhập không thông qua pattern
        Pattern pattern;
        // kiem tra ma nguoi nhap vao
        // ma nguoi 4 so
        //regex hoTen
        pattern = Pattern.compile("^[AÀẢÃÁẠĂẰẲẴẮẶÂẦẨẪẤẬBCDĐEÈẺẼÉẸÊỀỂỄẾỆFGHIÌỈĨÍỊJKLMNOÒỎÕÓỌÔỒỔỖỐỘƠỜỞỠỚỢPQRSTUÙỦŨÚỤƯỪỬỮỨỰVWXYỲỶỸÝỴZ][aàảãáạăằẳẵắặâầẩẫấậbcdđeèẻẽéẹêềểễếệfghiìỉĩíịjklmnoòỏõóọôồổỗốộơờởỡớợpqrstuùủũúụưừửữứựvwxyỳỷỹýỵz]+ [AÀẢÃÁẠĂẰẲẴẮẶÂẦẨẪẤẬBCDĐEÈẺẼÉẸÊỀỂỄẾỆFGHIÌỈĨÍỊJKLMNOÒỎÕÓỌÔỒỔỖỐỘƠỜỞỠỚỢPQRSTUÙỦŨÚỤƯỪỬỮỨỰVWXYỲỶỸÝỴZ][aàảãáạăằẳẵắặâầẩẫấậbcdđeèẻẽéẹêềểễếệfghiìỉĩíịjklmnoòỏõóọôồổỗốộơờởỡớợpqrstuùủũúụưừửữứựvwxyỳỷỹýỵz]+(?: [AÀẢÃÁẠĂẰẲẴẮẶÂẦẨẪẤẬBCDĐEÈẺẼÉẸÊỀỂỄẾỆFGHIÌỈĨÍỊJKLMNOÒỎÕÓỌÔỒỔỖỐỘƠỜỞỠỚỢPQRSTUÙỦŨÚỤƯỪỬỮỨỰVWXYỲỶỸÝỴZ][aàảãáạăằẳẵắặâầẩẫấậbcdđeèẻẽéẹêềểễếệfghiìỉĩíịjklmnoòỏõóọôồổỗốộơờởỡớợpqrstuùủũúụưừửữứựvwxyỳỷỹýỵz]*)*");
        if (!pattern.matcher(tfHoTen.getText()).matches()) {
            Alert alert = new Alert(Alert.AlertType.WARNING, "Hãy nhập vào họ tên hợp lệ!", ButtonType.OK);
            alert.setHeaderText(null);
            alert.showAndWait();
            return false;
        }

        //regex ngaysinh
        pattern = Pattern.compile("([12]\\d{3}-(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01]))");
        if (!pattern.matcher(tfTuNgay.getText()).matches()) {
            Alert alert = new Alert(Alert.AlertType.WARNING, "Hãy nhập vào ngày hợp lệ!", ButtonType.OK);
            alert.setHeaderText(null);
            alert.showAndWait();
            return false;
        }

        pattern = Pattern.compile("([12]\\d{3}-(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01]))");
        if (!pattern.matcher(tfDenNgay.getText()).matches()) {
            Alert alert = new Alert(Alert.AlertType.WARNING, "Hãy nhập vào ngày hợp lệ!", ButtonType.OK);
            alert.setHeaderText(null);
            alert.showAndWait();
            return false;
        }
        //sdt and cmnd
        //que quan, quan he and nghe nghiep
        pattern = Pattern.compile("/^(0?)(3[2-9]|5[6|8|9]|7[0|6-9]|8[0-6|8|9]|9[0-4|6-9])[0-9]{7}$/");
        if(tfSDT.getText().equals("")) {
            Alert alert = new Alert(Alert.AlertType.WARNING, "Hãy nhập vào sdt chuẩn", ButtonType.OK);
            alert.setHeaderText(null);
            alert.showAndWait();
            return false;
        }
        if(tfCMND.getText().equals("")) {
            Alert alert = new Alert(Alert.AlertType.WARNING, "Hãy nhập vào cmnd chuẩn", ButtonType.OK);
            alert.setHeaderText(null);
            alert.showAndWait();
            return false;
        }

        if(tfLiDo.getText().equals("")) {
            Alert alert = new Alert(Alert.AlertType.WARNING, "Hãy nhập vào lí do chính đáng", ButtonType.OK);
            alert.setHeaderText(null);
            alert.showAndWait();
            return false;
        }
        return true;
    }

}
