package controller;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.effect.SepiaTone;
import javafx.scene.input.MouseEvent;
import javafx.stage.Modality;
import javafx.stage.Stage;

import java.io.IOException;
import java.net.URL;
import java.util.Objects;
import java.util.ResourceBundle;

public class ControllerTamTruTamVang implements Initializable {
    @FXML
    private Button btDKTT;
    @FXML
    private Button btDKTV;
    @FXML
    private Button btTCTT;
    @FXML
    private Button btTCTV;

    // Event Listener on Button.onAction
    @FXML
    public void dkTamTru() throws IOException {
        // TODO Autogenerated
        Parent home = FXMLLoader.load(Objects.requireNonNull(getClass().getResource("/view/TamTruTamVang/dkTamTru.fxml")));
        Stage stage = new Stage();
        stage.setScene(new Scene(home,575,566));
        stage.setResizable(false);
        stage.initModality(Modality.APPLICATION_MODAL);
        stage.setTitle("Đăng ký tạm trú");
        stage.showAndWait();
    }
    // Event Listener on Button.onAction
    @FXML
    public void dkTamVang() throws IOException {
        // TODO Autogenerated
        Parent home = FXMLLoader.load(Objects.requireNonNull(getClass().getResource("/view/TamTruTamVang/dkTamVang.fxml")));
        Stage stage = new Stage();
        stage.setScene(new Scene(home,575,566));
        stage.setResizable(false);
        stage.initModality(Modality.APPLICATION_MODAL);
        stage.setTitle("Đăng ký tạm vắng");
        stage.showAndWait();
    }
    // Event Listener on Button.onAction
    @FXML
    public void traCuuTamtru() throws IOException {
        // TODO Autogenerated
        Parent home = FXMLLoader.load(Objects.requireNonNull(getClass().getResource("/view/TamTruTamVang/traCuuTamTru.fxml")));
        Stage stage = new Stage();
        stage.setScene(new Scene(home,575,566));
        stage.setResizable(false);
        stage.initModality(Modality.APPLICATION_MODAL);
        stage.setTitle("Tra cứu thông tin tạm trú");
        stage.showAndWait();
    }
    // Event Listener on Button.onAction
    @FXML
    public void traCuuTamVang() throws IOException {
        // TODO Autogenerated
        Parent home = FXMLLoader.load(Objects.requireNonNull(getClass().getResource("/view/TamTruTamVang/traCuuTamVang.fxml")));
        Stage stage = new Stage();
        stage.setScene(new Scene(home,575,566));
        stage.setResizable(false);
        stage.initModality(Modality.APPLICATION_MODAL);
        stage.setTitle("Tra cứu thông tin tạm vắng");
        stage.showAndWait();
    }

    @Override
    public void initialize(URL url, ResourceBundle resourceBundle) {
        btDKTT.addEventHandler(MouseEvent.MOUSE_MOVED, event -> btDKTT.setEffect(new SepiaTone()));
        btDKTT.addEventHandler(MouseEvent.MOUSE_EXITED, event -> btDKTT.setEffect(null));
        btDKTV.addEventHandler(MouseEvent.MOUSE_MOVED, event -> btDKTV.setEffect(new SepiaTone()));
        btDKTV.addEventHandler(MouseEvent.MOUSE_EXITED, event -> btDKTV.setEffect(null));
        btTCTT.addEventHandler(MouseEvent.MOUSE_MOVED, event -> btTCTT.setEffect(new SepiaTone()));
        btTCTT.addEventHandler(MouseEvent.MOUSE_EXITED, event -> btTCTT.setEffect(null));
        btTCTV.addEventHandler(MouseEvent.MOUSE_MOVED, event -> btTCTV.setEffect(new SepiaTone()));
        btTCTV.addEventHandler(MouseEvent.MOUSE_EXITED, event -> btTCTV.setEffect(null));
    }
}