package controller;

import javafx.fxml.FXML;
import javafx.event.ActionEvent;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

import java.io.IOException;

public class ControllerKhoanThu {

        // Event Listener on Button.onAction
        @FXML
        public void dkTamTru(ActionEvent event) throws IOException {
            // TODO Autogenerated
                Parent home = FXMLLoader.load(getClass().getResource("/view/TamTruTamVang/dkTamTru.fxml"));
                Stage stage = new Stage();
                stage.setScene(new Scene(home,575,566));
                stage.setResizable(false);
                stage.showAndWait();
        }
        // Event Listener on Button.onAction
        @FXML
        public void dkTamVang(ActionEvent event) throws IOException {
            // TODO Autogenerated
                Parent home = FXMLLoader.load(getClass().getResource("/view/TamTruTamVang/dkTamVang.fxml"));
                Stage stage = new Stage();
                stage.setScene(new Scene(home,575,566));
                stage.setResizable(false);
                stage.showAndWait();
        }
        // Event Listener on Button.onAction
        @FXML
        public void traCuuTamtru(ActionEvent event) throws IOException {
            // TODO Autogenerated
                Parent home = FXMLLoader.load(getClass().getResource("/view/TamTruTamVang/traCuuTamTru.fxml"));
                Stage stage = new Stage();
                stage.setScene(new Scene(home,575,566));
                stage.setResizable(false);
                stage.showAndWait();
        }
        // Event Listener on Button.onAction
        @FXML
        public void traCuuTamVang(ActionEvent event) throws IOException {
            // TODO Autogenerated
                Parent home = FXMLLoader.load(getClass().getResource("/view/TamTruTamVang/traCuuTamVang.fxml"));
                Stage stage = new Stage();
                stage.setScene(new Scene(home,575,566));
                stage.setResizable(false);
                stage.showAndWait();
        }

}
